INFO _internal.py:87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
ERROR demo.py:9 error manager
WARNING demo.py:10 warn manager
INFO demo.py:11 info manager
DEBUG demo.py:12 debug manager
INFO _internal.py:87 127.0.0.1 - - [18/Sep/2020 22:56:40] "GET /api/v1.0/index HTTP/1.1" 200 -
INFO _internal.py:87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/demo.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/modules.py', reloading
INFO _internal.py:87  * Restarting with stat
INFO _internal.py:87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [22/Sep/2020 21:58:11] "GET /api/v_1_0/index HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [22/Sep/2020 21:58:11] "GET /favicon.ico HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [22/Sep/2020 21:58:20] "GET /api_1_0/index HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [22/Sep/2020 21:58:22] "GET /api_1_0/index HTTP/1.1" 404 -
ERROR demo.py:9 error manager
WARNING demo.py:10 warn manager
INFO demo.py:11 info manager
DEBUG demo.py:12 debug manager
INFO _internal.py:87 192.168.0.105 - - [22/Sep/2020 21:59:25] "GET /api/v1.0/index HTTP/1.1" 200 -
ERROR demo.py:9 error manager
WARNING demo.py:10 warn manager
INFO demo.py:11 info manager
DEBUG demo.py:12 debug manager
INFO _internal.py:87 192.168.0.105 - - [22/Sep/2020 21:59:28] "GET /api/v1.0/index HTTP/1.1" 200 -
ERROR demo.py:9 error manager
WARNING demo.py:10 warn manager
INFO demo.py:11 info manager
DEBUG demo.py:12 debug manager
INFO _internal.py:87 192.168.0.105 - - [22/Sep/2020 21:59:32] "GET /api/v1.0/index HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/__init__.py', reloading
INFO _internal.py:87  * Restarting with stat
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
ERROR demo.py:9 error manager
WARNING demo.py:10 warn manager
INFO demo.py:11 info manager
DEBUG demo.py:12 debug manager
INFO _internal.py:87 192.168.0.105 - - [22/Sep/2020 22:24:01] "GET /api/v1.0/index HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [22/Sep/2020 22:25:03] "POST /api/v1.0/orders/payment HTTP/1.1" 405 -
INFO _internal.py:87 192.168.0.105 - - [22/Sep/2020 22:25:03] "POST /api/v1.0/orders/payment HTTP/1.1" 405 -
INFO _internal.py:87 192.168.0.105 - - [22/Sep/2020 22:25:03] "POST /api/v1.0/orders/payment HTTP/1.1" 405 -
INFO _internal.py:87 192.168.0.105 - - [22/Sep/2020 22:25:03] "POST /api/v1.0/orders/payment HTTP/1.1" 405 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/web_html.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/web_html.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
ERROR demo.py:9 error manager
WARNING demo.py:10 warn manager
INFO demo.py:11 info manager
DEBUG demo.py:12 debug manager
INFO _internal.py:87 192.168.0.105 - - [24/Sep/2020 21:40:06] "GET /api/v1.0/index HTTP/1.1" 200 -
ERROR demo.py:9 error manager
WARNING demo.py:10 warn manager
INFO demo.py:11 info manager
DEBUG demo.py:12 debug manager
INFO _internal.py:87 192.168.0.105 - - [24/Sep/2020 21:40:33] "GET /api/v1.0/index HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/demo.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/web_html.py', reloading
INFO _internal.py:87  * Restarting with stat
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
ERROR demo.py:10 error manager
WARNING demo.py:11 warn manager
INFO demo.py:12 info manager
DEBUG demo.py:13 debug manager
INFO _internal.py:87 192.168.0.105 - - [24/Sep/2020 21:43:11] "GET /api/v1.0/index HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/demo.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
ERROR demo.py:10 error manager
WARNING demo.py:11 warn manager
INFO demo.py:12 info manager
DEBUG demo.py:13 debug manager
INFO _internal.py:87 192.168.0.105 - - [24/Sep/2020 21:57:48] "GET /api/v1.0/index HTTP/1.1" 200 -
ERROR demo.py:10 error manager
WARNING demo.py:11 warn manager
INFO demo.py:12 info manager
DEBUG demo.py:13 debug manager
INFO _internal.py:87 192.168.0.105 - - [24/Sep/2020 21:57:56] "GET /api/v1.0/index HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/__init__.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [24/Sep/2020 22:47:35] "GET /api/v1.0/get_image_code HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:20:59] "GET /api/v1.0/get_image_code/1 HTTP/1.1" 500 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:20:59] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:20:59] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:20:59] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:21:00] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:21:00] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:21:00] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:22:22] "GET /api/v1.0/get_image_code/1 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:24:40] "GET /api/v1.0/get_image_code/1 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:29:33] "GET //api/v1.0/get_image_code/1 HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:29:46] "GET //api/v1.0/get_image_code/1 HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:29:58] "GET //api/v1.0/get_image_code/1 HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:30:41] "GET //api/v1.0/get_image_code/1 HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:31:01] "GET //api/v1.0/get_image_code/1 HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:31:33] "GET //api/v1.0/get_image_code/2 HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:32:16] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:32:22] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:32:58] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:33:31] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:35:08] "GET /babel/core/lib/transformation/file/file.js HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:35:08] "GET /babel/traverse/lib/path/index.js HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:35:08] "GET /babel/plugin-transform-typescript/lib/index.js HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:35:08] "GET /babel/traverse/lib/visitors.js HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:35:08] "GET /babel/traverse/lib/path/context.js HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:35:08] "GET /babel/traverse/lib/context.js HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:35:08] "GET /babel/core/lib/transformation/file/file.js HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:35:08] "GET /babel/traverse/lib/path/index.js HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:35:08] "GET /babel/plugin-transform-typescript/lib/index.js HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:35:08] "GET /babel/traverse/lib/visitors.js HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:35:08] "GET /babel/traverse/lib/path/context.js HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:35:08] "GET /babel/traverse/lib/context.js HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:36:26] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:39:18] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:41:21] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:41:44] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:44:13] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:48:12] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:48:35] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:48:35] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:49:08] "GET /api/v1.0/get_image_code/0 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:49:14] "GET /api/v1.0/get_image_code/71 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:49:27] "GET /api/v1.0/get_image_code/66 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:50:31] "GET /api/v1.0/get_image_code/9 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:50:44] "GET /api/v1.0/get_image_code/6 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:51:03] "GET /api/v1.0/get_image_code/20 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:51:49] "GET /api/v1.0/get_image_code/10 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:55:51] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:56:00] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:56:12] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:56:19] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:57:09] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 500 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:57:22] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 500 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:59:00] "GET /api/v1.0/get_image_code/1 HTTP/1.1" 500 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:59:00] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:59:00] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:59:00] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:59:00] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:59:00] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:59:00] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:59:40] "GET /api/v1.0/get_image_code/1 HTTP/1.1" 500 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:59:40] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:59:40] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:59:40] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:59:40] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:59:40] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:00:04] "GET /api/v1.0/get_image_code/1 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:00:42] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 500 -
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:00:56] "GET /api/v1.0/get_image_code/1 HTTP/1.1" 500 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:00:56] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:00:56] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:00:56] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:00:57] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:00:57] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:00:57] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:05:17] "GET /api/v1.0/get_image_code/1 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:05:43] "GET /api/v1.0/get_image_code/1 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:08:34] "GET /api/v1.0/get_image_code/1 HTTP/1.1" 500 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:08:34] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:08:34] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:08:34] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:08:34] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:08:34] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:08:34] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:13:43] "GET /api/v1.0/get_image_code/1 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:15:17] "GET /api/v1.0/get_image_code/19 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:15:17] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:15:17] "GET /api/v1.0/get_image_code/93 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:15:17] "GET /api/v1.0/get_image_code/98 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:15:21] "GET /api/v1.0/get_image_code/60 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.108 - - [27/Sep/2020 22:22:05] "GET /api/v_1_0/get_image_code/2 HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.108 - - [27/Sep/2020 22:22:05] "GET /favicon.ico HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.108 - - [27/Sep/2020 22:22:21] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.108 - - [27/Sep/2020 22:22:50] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.108 - - [27/Sep/2020 22:23:14] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.108 - - [27/Sep/2020 22:23:18] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.108 - - [27/Sep/2020 22:23:19] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.108 - - [27/Sep/2020 22:23:33] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.100 - - [27/Sep/2020 22:31:36] "GET /api/v1.0/get_image_code/1 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.108 - - [27/Sep/2020 22:33:51] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 500 -
INFO _internal.py:87 192.168.0.108 - - [27/Sep/2020 22:33:51] "GET /api/v1.0/get_image_code/2?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.108 - - [27/Sep/2020 22:33:51] "GET /api/v1.0/get_image_code/2?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.108 - - [27/Sep/2020 22:33:51] "GET /api/v1.0/get_image_code/2?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.108 - - [27/Sep/2020 22:33:52] "GET /api/v1.0/get_image_code/2?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.108 - - [27/Sep/2020 22:33:52] "GET /api/v1.0/get_image_code/2?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.108 - - [27/Sep/2020 22:34:11] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [29/Sep/2020 20:39:38] "GET /favicon.ico HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [29/Sep/2020 20:39:38] "GET /api/v1.0/get_image_code/84 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [29/Sep/2020 20:39:38] "GET /register HTTP/1.1" 404 -
