INFO _internal.py:87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
ERROR demo.py:9 error manager
WARNING demo.py:10 warn manager
INFO demo.py:11 info manager
DEBUG demo.py:12 debug manager
INFO _internal.py:87 127.0.0.1 - - [18/Sep/2020 22:56:40] "GET /api/v1.0/index HTTP/1.1" 200 -
INFO _internal.py:87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/demo.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/modules.py', reloading
INFO _internal.py:87  * Restarting with stat
INFO _internal.py:87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [22/Sep/2020 21:58:11] "GET /api/v_1_0/index HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [22/Sep/2020 21:58:11] "GET /favicon.ico HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [22/Sep/2020 21:58:20] "GET /api_1_0/index HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [22/Sep/2020 21:58:22] "GET /api_1_0/index HTTP/1.1" 404 -
ERROR demo.py:9 error manager
WARNING demo.py:10 warn manager
INFO demo.py:11 info manager
DEBUG demo.py:12 debug manager
INFO _internal.py:87 192.168.0.105 - - [22/Sep/2020 21:59:25] "GET /api/v1.0/index HTTP/1.1" 200 -
ERROR demo.py:9 error manager
WARNING demo.py:10 warn manager
INFO demo.py:11 info manager
DEBUG demo.py:12 debug manager
INFO _internal.py:87 192.168.0.105 - - [22/Sep/2020 21:59:28] "GET /api/v1.0/index HTTP/1.1" 200 -
ERROR demo.py:9 error manager
WARNING demo.py:10 warn manager
INFO demo.py:11 info manager
DEBUG demo.py:12 debug manager
INFO _internal.py:87 192.168.0.105 - - [22/Sep/2020 21:59:32] "GET /api/v1.0/index HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/__init__.py', reloading
INFO _internal.py:87  * Restarting with stat
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
ERROR demo.py:9 error manager
WARNING demo.py:10 warn manager
INFO demo.py:11 info manager
DEBUG demo.py:12 debug manager
INFO _internal.py:87 192.168.0.105 - - [22/Sep/2020 22:24:01] "GET /api/v1.0/index HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [22/Sep/2020 22:25:03] "POST /api/v1.0/orders/payment HTTP/1.1" 405 -
INFO _internal.py:87 192.168.0.105 - - [22/Sep/2020 22:25:03] "POST /api/v1.0/orders/payment HTTP/1.1" 405 -
INFO _internal.py:87 192.168.0.105 - - [22/Sep/2020 22:25:03] "POST /api/v1.0/orders/payment HTTP/1.1" 405 -
INFO _internal.py:87 192.168.0.105 - - [22/Sep/2020 22:25:03] "POST /api/v1.0/orders/payment HTTP/1.1" 405 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/web_html.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/web_html.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
ERROR demo.py:9 error manager
WARNING demo.py:10 warn manager
INFO demo.py:11 info manager
DEBUG demo.py:12 debug manager
INFO _internal.py:87 192.168.0.105 - - [24/Sep/2020 21:40:06] "GET /api/v1.0/index HTTP/1.1" 200 -
ERROR demo.py:9 error manager
WARNING demo.py:10 warn manager
INFO demo.py:11 info manager
DEBUG demo.py:12 debug manager
INFO _internal.py:87 192.168.0.105 - - [24/Sep/2020 21:40:33] "GET /api/v1.0/index HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/demo.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/web_html.py', reloading
INFO _internal.py:87  * Restarting with stat
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
ERROR demo.py:10 error manager
WARNING demo.py:11 warn manager
INFO demo.py:12 info manager
DEBUG demo.py:13 debug manager
INFO _internal.py:87 192.168.0.105 - - [24/Sep/2020 21:43:11] "GET /api/v1.0/index HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/demo.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
ERROR demo.py:10 error manager
WARNING demo.py:11 warn manager
INFO demo.py:12 info manager
DEBUG demo.py:13 debug manager
INFO _internal.py:87 192.168.0.105 - - [24/Sep/2020 21:57:48] "GET /api/v1.0/index HTTP/1.1" 200 -
ERROR demo.py:10 error manager
WARNING demo.py:11 warn manager
INFO demo.py:12 info manager
DEBUG demo.py:13 debug manager
INFO _internal.py:87 192.168.0.105 - - [24/Sep/2020 21:57:56] "GET /api/v1.0/index HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/__init__.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [24/Sep/2020 22:47:35] "GET /api/v1.0/get_image_code HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:20:59] "GET /api/v1.0/get_image_code/1 HTTP/1.1" 500 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:20:59] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:20:59] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:20:59] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:21:00] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:21:00] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:21:00] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:22:22] "GET /api/v1.0/get_image_code/1 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:24:40] "GET /api/v1.0/get_image_code/1 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:29:33] "GET //api/v1.0/get_image_code/1 HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:29:46] "GET //api/v1.0/get_image_code/1 HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:29:58] "GET //api/v1.0/get_image_code/1 HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:30:41] "GET //api/v1.0/get_image_code/1 HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:31:01] "GET //api/v1.0/get_image_code/1 HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:31:33] "GET //api/v1.0/get_image_code/2 HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:32:16] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:32:22] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:32:58] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:33:31] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:35:08] "GET /babel/core/lib/transformation/file/file.js HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:35:08] "GET /babel/traverse/lib/path/index.js HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:35:08] "GET /babel/plugin-transform-typescript/lib/index.js HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:35:08] "GET /babel/traverse/lib/visitors.js HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:35:08] "GET /babel/traverse/lib/path/context.js HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:35:08] "GET /babel/traverse/lib/context.js HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:35:08] "GET /babel/core/lib/transformation/file/file.js HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:35:08] "GET /babel/traverse/lib/path/index.js HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:35:08] "GET /babel/plugin-transform-typescript/lib/index.js HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:35:08] "GET /babel/traverse/lib/visitors.js HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:35:08] "GET /babel/traverse/lib/path/context.js HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:35:08] "GET /babel/traverse/lib/context.js HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:36:26] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:39:18] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:41:21] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:41:44] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:44:13] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:48:12] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:48:35] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:48:35] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:49:08] "GET /api/v1.0/get_image_code/0 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:49:14] "GET /api/v1.0/get_image_code/71 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:49:27] "GET /api/v1.0/get_image_code/66 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:50:31] "GET /api/v1.0/get_image_code/9 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:50:44] "GET /api/v1.0/get_image_code/6 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:51:03] "GET /api/v1.0/get_image_code/20 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:51:49] "GET /api/v1.0/get_image_code/10 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:55:51] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:56:00] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:56:12] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:56:19] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:57:09] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 500 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:57:22] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 500 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:59:00] "GET /api/v1.0/get_image_code/1 HTTP/1.1" 500 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:59:00] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:59:00] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:59:00] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:59:00] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:59:00] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:59:00] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:59:40] "GET /api/v1.0/get_image_code/1 HTTP/1.1" 500 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:59:40] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:59:40] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:59:40] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:59:40] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 20:59:40] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:00:04] "GET /api/v1.0/get_image_code/1 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:00:42] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 500 -
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:00:56] "GET /api/v1.0/get_image_code/1 HTTP/1.1" 500 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:00:56] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:00:56] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:00:56] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:00:57] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:00:57] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:00:57] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:05:17] "GET /api/v1.0/get_image_code/1 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:05:43] "GET /api/v1.0/get_image_code/1 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:08:34] "GET /api/v1.0/get_image_code/1 HTTP/1.1" 500 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:08:34] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:08:34] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:08:34] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:08:34] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:08:34] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:08:34] "GET /api/v1.0/get_image_code/1?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:13:43] "GET /api/v1.0/get_image_code/1 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:15:17] "GET /api/v1.0/get_image_code/19 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:15:17] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:15:17] "GET /api/v1.0/get_image_code/93 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:15:17] "GET /api/v1.0/get_image_code/98 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [27/Sep/2020 21:15:21] "GET /api/v1.0/get_image_code/60 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.108 - - [27/Sep/2020 22:22:05] "GET /api/v_1_0/get_image_code/2 HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.108 - - [27/Sep/2020 22:22:05] "GET /favicon.ico HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.108 - - [27/Sep/2020 22:22:21] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.108 - - [27/Sep/2020 22:22:50] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.108 - - [27/Sep/2020 22:23:14] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.108 - - [27/Sep/2020 22:23:18] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.108 - - [27/Sep/2020 22:23:19] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.108 - - [27/Sep/2020 22:23:33] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.100 - - [27/Sep/2020 22:31:36] "GET /api/v1.0/get_image_code/1 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.108 - - [27/Sep/2020 22:33:51] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 500 -
INFO _internal.py:87 192.168.0.108 - - [27/Sep/2020 22:33:51] "GET /api/v1.0/get_image_code/2?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.108 - - [27/Sep/2020 22:33:51] "GET /api/v1.0/get_image_code/2?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.108 - - [27/Sep/2020 22:33:51] "GET /api/v1.0/get_image_code/2?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.108 - - [27/Sep/2020 22:33:52] "GET /api/v1.0/get_image_code/2?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.108 - - [27/Sep/2020 22:33:52] "GET /api/v1.0/get_image_code/2?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.108 - - [27/Sep/2020 22:34:11] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [29/Sep/2020 20:39:38] "GET /favicon.ico HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [29/Sep/2020 20:39:38] "GET /api/v1.0/get_image_code/84 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [29/Sep/2020 20:39:38] "GET /register HTTP/1.1" 404 -
INFO _internal.py:87  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [12/Oct/2020 21:37:49] "GET /api/v1.0/get_image_code/96 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.108 - - [13/Oct/2020 20:59:57] "GET /api/v1.0//get_image_code/15701229789 HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.108 - - [13/Oct/2020 21:00:14] "GET /api/v1.0/get_image_code/15701229789 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.108 - - [13/Oct/2020 21:00:40] "GET /api/v1.0/get_image_code/15701229789?image_code_id&image_code HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [13/Oct/2020 21:02:09] "GET /api/v1.0/get_image_code/98 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [13/Oct/2020 21:02:17] "GET /api/v1.0/get_image_code/2 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [13/Oct/2020 21:02:19] "GET /api/v1.0/get_image_code/12 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [13/Oct/2020 21:02:22] "GET /api/v1.0/get_image_code/46 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [13/Oct/2020 21:03:02] "GET /api/v1.0/get_image_code/84 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [13/Oct/2020 21:04:21] "GET /api/v1.0/get_image_code/15 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.108 - - [13/Oct/2020 21:05:27] "GET /api/v1.0/get_image_code/15701229789?image_code_id=694b1041-0881-446f-98c4-33e04faea6c7&image_code=OLIY HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.108 - - [13/Oct/2020 21:06:04] "GET /api/v1.0/sms_codes/15701229789?image_code_id=694b1041-0881-446f-98c4-33e04faea6c7&image_code=OLIY HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.108 - - [13/Oct/2020 21:06:50] "GET /api/v1.0/sms_codes/15701229789?image_code_id=c5f547d3-6785-488b-a587-10b6b27ac476&image_code=YMCB HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [13/Oct/2020 21:08:05] "GET /api/v1.0/get_image_code/3 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [13/Oct/2020 21:18:58] "GET /api/v1.0/get_image_code/81 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.108 - - [13/Oct/2020 21:19:28] "GET /api/v1.0/sms_codes/15701229789?image_code_id=694b1041-0881-446f-98c4-33e04faea6c7&image_code=YMCB HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.108 - - [13/Oct/2020 21:19:39] "GET /api/v1.0/sms_codes/15701229789?image_code_id=694b1041-0881-446f-98c4-33e04faea6c7&image_code=YMCB HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.108 - - [13/Oct/2020 21:19:44] "GET /api/v1.0/sms_codes/15701229789?image_code_id=694b1041-0881-446f-98c4-33e04faea6c7&image_code=YMCB HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [13/Oct/2020 21:20:05] "GET /api/v1.0/get_image_code/19 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [13/Oct/2020 21:20:10] "GET /api/v1.0/get_image_code/95 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.108 - - [13/Oct/2020 21:20:52] "GET /api/v1.0/sms_codes/15701229789?image_code_id=694b1041-0881-446f-98c4-33e04faea6c7&image_code=YMCB HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [13/Oct/2020 21:21:29] "GET /api/v1.0/get_image_code/54 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.108 - - [13/Oct/2020 21:22:05] "GET /api/v1.0/sms_codes/15701229789?image_code_id=c5f547d3-6785-488b-a587-10b6b27ac476&image_code=MLSC HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [13/Oct/2020 21:40:32] "GET /api/v1.0/get_image_code/64 HTTP/1.1" 200 -
ERROR verify_code.py:137 send_template_sms() takes exactly 4 arguments (3 given)
INFO _internal.py:87 192.168.0.108 - - [13/Oct/2020 21:41:28] "GET /api/v1.0/sms_codes/15701229789?image_code_id=64&image_code=UPSP HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [13/Oct/2020 21:42:13] "GET /api/v1.0/get_image_code/90 HTTP/1.1" 200 -
ERROR verify_code.py:136 send_template_sms() takes exactly 4 arguments (3 given)
INFO _internal.py:87 192.168.0.108 - - [13/Oct/2020 21:42:37] "GET /api/v1.0/sms_codes/15701229789?image_code_id=90&image_code=M8LJ HTTP/1.1" 500 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [13/Oct/2020 21:43:51] "GET /api/v1.0/get_image_code/54 HTTP/1.1" 200 -
ERROR verify_code.py:137 send_template_sms() takes exactly 4 arguments (3 given)
INFO _internal.py:87 192.168.0.108 - - [13/Oct/2020 21:44:14] "GET /api/v1.0/sms_codes/15701229789?image_code_id=54&image_code=ZUHM HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [13/Oct/2020 21:45:54] "GET /api/v1.0/get_image_code/76 HTTP/1.1" 200 -
ERROR verify_code.py:136 send_template_sms() takes exactly 4 arguments (3 given)
INFO _internal.py:87 192.168.0.108 - - [13/Oct/2020 21:46:28] "GET /api/v1.0/sms_codes/15701229789?image_code_id=76&image_code=ZFQH HTTP/1.1" 500 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [13/Oct/2020 21:47:19] "GET /api/v1.0/get_image_code/95 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.108 - - [13/Oct/2020 21:47:44] "GET /api/v1.0/sms_codes/15701229789?image_code_id=95&image_code=RPPQ HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [13/Oct/2020 22:02:03] "GET /api/v1.0/get_image_code/95 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [13/Oct/2020 22:02:30] "GET /api/v1.0/get_image_code/37 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [13/Oct/2020 22:02:45] "GET /api/v1.0/get_image_code/69 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [13/Oct/2020 22:02:50] "GET /api/v1.0/get_image_code/78 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [13/Oct/2020 22:03:03] "GET /api/v1.0/get_image_code/16 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [13/Oct/2020 22:05:25] "GET /api/v1.0/get_image_code/90 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [13/Oct/2020 22:08:20] "GET /api/v1.0/get_image_code/99 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [13/Oct/2020 22:08:51] "GET /api/v1.0/get_image_code/23 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.108 - - [13/Oct/2020 22:09:15] "GET /api/v1.0/sms_codes?image_code_id=23&image_code=KFTE&mobile=15701229789 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [13/Oct/2020 22:13:08] "GET /babel/parser/lib/index.js HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [13/Oct/2020 22:13:08] "GET /babel/parser/lib/index.js HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 20:43:18] "GET /babel/parser/lib/index.js HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 20:43:18] "GET /babel/parser/lib/index.js HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 20:52:04] "GET /babel/parser/lib/index.js HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 20:52:04] "GET /babel/parser/lib/index.js HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 20:56:24] "GET /api/v1.0/get_image_code/10 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 20:56:39] "GET /api/v1.0/get_image_code/28 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 20:56:52] "GET /api/v1.0/get_image_code/16 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 20:57:11] "GET /api/v1.0/get_image_code/42 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 20:58:30] "GET /api/v1.0/get_image_code/85 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 20:59:17] "GET /api/v1.0/get_image_code/27 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 20:59:40] "GET /api/v1.0/get_image_code/57 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 21:00:34] "GET /api/v1.0/get_image_code/42 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 21:02:44] "GET /api/v1.0/get_image_code/51 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 21:02:59] "GET /api/v1.0/get_image_code/52 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 21:03:02] "GET /api/v1.0/get_image_code/3 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 21:03:05] "GET /api/v1.0/get_image_code/63 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 21:03:42] "GET /api/v1.0/get_image_code/87 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 21:03:52] "GET /api/v1.0/get_image_code/95 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 21:04:04] "GET /api/v1.0/get_image_code/60 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 21:04:09] "GET /api/v1.0/get_image_code/38 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 21:14:42] "GET /api/v1.0/get_image_code/13 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 21:16:12] "GET /api/v1.0/get_image_code/82 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 21:16:51] "GET /api/v1.0/get_image_code/48 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 21:16:57] "GET /api/v1.0/get_image_code/31 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 21:17:46] "GET /api/v1.0/get_image_code/71 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 21:18:14] "GET /api/v1.0/get_image_code/89 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 21:18:44] "GET /api/v1.0/get_image_code/57 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 21:18:52] "GET /api/v1.0/get_image_code/94 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 21:19:27] "GET /api/v1.0/get_image_code/99 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 21:19:57] "GET /api/v1.0/get_image_code/99 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 21:20:14] "GET /api/v1.0/get_image_code/41 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 21:20:16] "GET /api/v1.0/get_image_code/49 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 21:20:16] "GET /api/v1.0/get_image_code/11 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 21:20:16] "GET /api/v1.0/get_image_code/3 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 21:20:17] "GET /api/v1.0/get_image_code/45 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 21:20:17] "GET /api/v1.0/get_image_code/57 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 21:20:18] "GET /api/v1.0/get_image_code/19 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 21:20:19] "GET /api/v1.0/get_image_code/47 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 21:20:19] "GET /api/v1.0/get_image_code/62 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 21:20:19] "GET /api/v1.0/get_image_code/25 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 21:20:19] "GET /api/v1.0/get_image_code/72 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 21:20:20] "GET /api/v1.0/get_image_code/21 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 21:20:20] "GET /api/v1.0/get_image_code/22 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 21:20:21] "GET /api/v1.0/get_image_code/38 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 21:20:21] "GET /api/v1.0/get_image_code/7 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 21:20:22] "GET /api/v1.0/get_image_code/0 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 21:20:22] "GET /api/v1.0/get_image_code/54 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.108 - - [14/Oct/2020 22:15:23] "GET /api/v1.0/get_image_code?image_code_id=12 HTTP/1.1" 500 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.108 - - [14/Oct/2020 22:16:12] "GET /api/v1.0/get_image_code?image_code_id=12 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.108 - - [14/Oct/2020 22:17:30] "GET /api/v1.0/get_image_code?image_code_id=12 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.108 - - [14/Oct/2020 22:18:01] "GET /api/v1.0/get_image_code?image_code_id=12 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.108 - - [14/Oct/2020 22:19:14] "GET /api/v1.0/get_image_code?image_code_id=12 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.108 - - [14/Oct/2020 22:20:24] "GET /api/v1.0/get_image_code?image_code_id=12 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
ERROR verify_code.py:36 global name 'image_code_id' is not defined
INFO _internal.py:87 192.168.0.108 - - [14/Oct/2020 22:21:52] "GET /api/v1.0/get_image_code?image_code_id=12 HTTP/1.1" 200 -
INFO _internal.py:87  * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
ERROR verify_code.py:36 global name 'image_code_id' is not defined
INFO _internal.py:87 192.168.0.108 - - [14/Oct/2020 22:22:07] "GET /api/v1.0/get_image_code?image_code_id=12 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.108 - - [14/Oct/2020 22:22:31] "GET /api/v1.0/get_image_code?image_code_id=12 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 22:23:25] "GET /api/v1.0/get_image_code/87 HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 22:24:07] "GET /api/v1.0/get_image_code/86 HTTP/1.1" 404 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 22:28:09] "GET /api/v1.0/get_image_code HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 22:28:20] "GET /api/v1.0/get_image_code HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 22:28:57] "GET /api/v1.0/get_image_code HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 22:29:38] "GET /api/v1.0/get_image_code?image_code_id=1234 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 22:29:53] "GET /api/v1.0/get_image_code?image_code_id=1234 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.108 - - [14/Oct/2020 22:46:33] "GET /api/v1.0/get_image_code?image_code_id=12 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.108 - - [14/Oct/2020 22:46:41] "GET /api/v1.0/get_image_code?image_code_id=12 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.108 - - [14/Oct/2020 22:47:02] "GET /api/v1.0/get_image_code?image_code_id=12 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.108 - - [14/Oct/2020 22:47:24] "GET /api/v1.0/get_image_code?image_code_id=12 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.108 - - [14/Oct/2020 22:47:42] "GET /api/v1.0/get_image_code?image_code_id=12 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.108 - - [14/Oct/2020 22:49:53] "GET /api/v1.0/get_image_code?image_code_id=12 HTTP/1.1" 500 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.108 - - [14/Oct/2020 22:51:29] "GET /api/v1.0/get_image_code?image_code_id=12 HTTP/1.1" 500 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.108 - - [14/Oct/2020 22:51:46] "GET /api/v1.0/get_image_code?image_code_id=12 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.108 - - [14/Oct/2020 22:52:14] "GET /api/v1.0/get_image_code?image_code_id=12 HTTP/1.1" 500 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.108 - - [14/Oct/2020 22:52:51] "GET /api/v1.0/get_image_code?image_code_id=12 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 22:52:58] "GET /api/v1.0/get_image_code?image_code_id=1234 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.108 - - [14/Oct/2020 22:53:22] "GET /api/v1.0/get_image_code?image_code_id=12 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 22:53:26] "GET /api/v1.0/get_image_code?image_code_id=1234 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 22:58:44] "GET /api/v1.0/get_image_code?image_code_id=1234 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 22:58:51] "GET /api/v1.0/get_image_code?image_code_id=1234 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 22:58:55] "GET /api/v1.0/get_image_code?image_code_id=1234 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:01:29] "GET /api/v1.0/get_image_code?image_code_id=1234 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:01:39] "GET /api/v1.0/get_image_code?image_code_id=1234 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:01:52] "GET /api/v1.0/get_image_code?image_code_id=1234 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:01:59] "GET /api/v1.0/get_image_code?image_code_id=1234 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:02:42] "GET /api/v1.0/get_image_code?image_code_id=1234 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:02:47] "GET /api/v1.0/get_image_code?image_code_id=1234 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.108 - - [14/Oct/2020 23:06:05] "GET /api/v1.0/get_image_code?image_code_id=12 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.108 - - [14/Oct/2020 23:06:38] "GET /api/v1.0/get_image_code?image_code_id=12 HTTP/1.1" 500 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:13:43] "GET /api/v1.0/get_image_code?[object%20Object] HTTP/1.1" 500 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:14:02] "GET /api/v1.0/get_image_code?image_code_id=2858987990266 HTTP/1.1" 500 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:14:29] "GET /api/v1.0/get_image_code?image_code_id=80670745881432 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:14:50] "GET /api/v1.0/get_image_code?image_code_id=57924871488502 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:15:23] "GET /api/v1.0/get_image_code?image_code_id=85586504224200 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:15:55] "GET /api/v1.0/get_image_code?image_code_id=9840250481529 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:16:12] "GET /api/v1.0/get_image_code?image_code_id=45705132014450 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:16:42] "GET /api/v1.0/get_image_code?image_code_id=23289879100975 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:17:17] "GET /api/v1.0/get_image_code?image_code_id=45997495600695 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:17:34] "GET /api/v1.0/get_image_code?image_code_id=9826146469403 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:18:10] "GET /api/v1.0/get_image_code?image_code_id=45611255300365 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:18:48] "GET /api/v1.0/get_image_code?image_code_id=99953051433823 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:20:21] "GET /api/v1.0/get_image_code?image_code_id=92832704146109 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:21:42] "GET /api/v1.0/get_image_code?image_code_id=68995350451996 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:22:19] "GET /api/v1.0/get_image_code?image_code_id=70519899551320 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:23:22] "GET /api/v1.0/get_image_code?image_code_id=62340287512936 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:23:50] "GET /api/v1.0/get_image_code?image_code_id=95354247468001 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:24:17] "GET /api/v1.0/get_image_code?image_code_id=5726131813180 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:24:41] "GET /api/v1.0/get_image_code?image_code_id=37035737767436 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:25:48] "GET /api/v1.0/get_image_code?image_code_id=86180391877532 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:26:31] "GET /api/v1.0/get_image_code?image_code_id=77324640966874 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:26:59] "GET /api/v1.0/get_image_code?image_code_id=70890623381940 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:27:07] "GET /api/v1.0/get_image_code?image_code_id=93853144359433 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:28:04] "GET /api/v1.0/get_image_code?image_code_id=47000633581350 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:29:55] "GET /api/v1.0/get_image_code?image_code_id=97895482350921 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:31:52] "GET /api/v1.0/get_image_code?image_code_id=61914900523622 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:31:59] "GET /api/v1.0/get_image_code?image_code_id=99540220893288 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:32:22] "GET /api/v1.0/get_image_code?image_code_id=12668505535812 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:32:46] "GET /api/v1.0/get_image_code?image_code_id=22394271884892 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:32:53] "GET /api/v1.0/get_image_code?image_code_id=40351881229498 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:33:54] "GET /api/v1.0/get_image_code?image_code_id=95265254178574 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:34:25] "GET /api/v1.0/get_image_code?image_code_id=62482587410525 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:36:40] "GET /api/v1.0/get_image_code?image_code_id=44680840563620 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:36:55] "GET /api/v1.0/get_image_code?image_code_id=20303006099780 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:39:11] "GET /api/v1.0/get_image_code?image_code_id=69280489405878 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:42:01] "GET /api/v1.0/get_image_code?image_code_id=99986598674234 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [14/Oct/2020 23:42:21] "GET /api/v1.0/get_image_code?image_code_id=27673284181856 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/usr/lib/python2.7/lib-dynload/termios.x86_64-linux-gnu.so', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
INFO _internal.py:87 192.168.0.105 - - [15/Oct/2020 21:09:28] "GET /api/v1.0/get_image_code?image_code_id=16570730295338 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [15/Oct/2020 21:10:15] "GET /api/v1.0/get_image_code?image_code_id=58201707104885 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [15/Oct/2020 21:10:26] "GET /api/v1.0/get_image_code?image_code_id=73106204753257 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [15/Oct/2020 21:11:00] "GET /api/v1.0/get_image_code?image_code_id=127847191775 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [15/Oct/2020 21:13:48] "GET /api/v1.0/get_image_code?image_code_id=37430236836131 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [15/Oct/2020 21:14:28] "GET /api/v1.0/get_image_code?image_code_id=43425959669622 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [15/Oct/2020 21:14:43] "GET /api/v1.0/get_image_code?image_code_id=55690849594458 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [15/Oct/2020 21:14:52] "GET /api/v1.0/get_image_code?image_code_id=94877609223570 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [15/Oct/2020 21:15:01] "GET /api/v1.0/get_image_code?image_code_id=51008683465272 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [15/Oct/2020 21:15:02] "GET /api/v1.0/get_image_code?image_code_id=31431302333647 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [15/Oct/2020 21:15:03] "GET /api/v1.0/get_image_code?image_code_id=96840265978180 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [15/Oct/2020 21:15:03] "GET /api/v1.0/get_image_code?image_code_id=81853802183937 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [15/Oct/2020 21:15:04] "GET /api/v1.0/get_image_code?image_code_id=88871215140402 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [15/Oct/2020 21:15:04] "GET /api/v1.0/get_image_code?image_code_id=5420874904259 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [15/Oct/2020 21:15:05] "GET /api/v1.0/get_image_code?image_code_id=26435615895450 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [15/Oct/2020 21:15:09] "GET /api/v1.0/get_image_code?image_code_id=95815250570264 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [15/Oct/2020 21:16:18] "GET /api/v1.0/get_image_code?image_code_id=43664287767433 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [15/Oct/2020 21:19:26] "GET /api/v1.0/get_image_code?image_code_id=24439664003181 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [15/Oct/2020 21:19:37] "GET /api/v1.0/get_image_code?image_code_id=93309792310119 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [15/Oct/2020 21:19:38] "GET /api/v1.0/get_image_code?image_code_id=48687323847028 HTTP/1.1" 200 -
INFO _internal.py:87 192.168.0.105 - - [15/Oct/2020 21:19:49] "GET /api/v1.0/get_image_code?image_code_id=10278439512891 HTTP/1.1" 200 -
INFO _internal.py:87  * Detected change in '/home/focusdroid/flask/ihome_python004/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:87  * Restarting with stat
WARNING _internal.py:87  * Debugger is active!
INFO _internal.py:87  * Debugger PIN: 140-095-645
